export const DEPARTAMENTOS = [
  "Amazonas",
  "Antioquia",
  "Arauca",
  "Atlántico",
  "Bogotá D.C.",
  "Bolívar",
  "Boyacá",
  "Caldas",
  "Caquetá",
  "Casanare",
  "Cauca",
  "Cesar",
  "Chocó",
  "Córdoba",
  "Cundinamarca",
  "Guainía",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte de Santander",
  "Putumayo",
  "Quindío",
  "Risaralda",
  "San Andrés y Providencia",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca",
  "Vaupés",
  "Vichada",
];

export const CIUDADES = {
  "Amazonas": [
    "Leticia", "Puerto Nariño", "La Chorrera", "La Pedrera", "Tarapacá",
    "El Encanto", "La Victoria", "Mirití-Paraná", "Puerto Arica", "Puerto Alegría",
  ],
  "Antioquia": [
    "Medellín", "Bello", "Itagüí", "Envigado", "Sabaneta", "La Estrella",
    "Caldas", "Copacabana", "Girardota", "Barbosa", "Rionegro", "El Carmen de Viboral",
    "Marinilla", "Guarne", "La Ceja", "El Santuario", "Sonsón", "Abejorral",
    "Jardín", "Jericó", "Andes", "Ciudad Bolívar", "Betulia", "Santa Fe de Antioquia",
    "Sopetrán", "San Jerónimo", "Olaya", "Liborina", "Cañasgordas", "Uramita",
    "Frontino", "Dabeiba", "Mutatá", "Chigorodó", "Carepa", "Apartadó", "Turbo",
    "Necoclí", "San Pedro de Urabá", "Arboletes", "San Juan de Urabá",
    "Caucasia", "Taraza", "Cáceres", "Zaragoza", "El Bagre", "Nechí",
    "Segovia", "Remedios", "Puerto Berrío", "Puerto Nare", "Puerto Triunfo",
    "San Luis", "Cocorná", "Granada", "San Carlos", "San Rafael", "San Roque",
    "Santa Bárbara", "Fredonia", "Caramanta", "Valparaíso", "Támesis",
    "Yarumal", "Angostura", "Ituango", "Valdivia", "Campamento", "Guadalupe",
    "Gómez Plata", "Amalfi", "Yolombó", "Yalí", "Cisneros", "San Vicente",
    "Donmatías", "Santa Rosa de Osos", "San Pedro de los Milagros", "Entrerríos",
    "Belmira", "San José de la Montaña", "Buriticá", "Sabanalarga", "Peque",
    "Toledo", "Montebello", "Alejandría", "Concepción", "Retiro",
  ],
  "Arauca": [
    "Arauca", "Saravena", "Tame", "Fortul", "Arauquita", "Cravo Norte", "Puerto Rondón",
  ],
  "Atlántico": [
    "Barranquilla", "Soledad", "Malambo", "Galapa", "Puerto Colombia",
    "Sabanagrande", "Sabanalarga", "Baranoa", "Usiacurí", "Juan de Acosta",
    "Piojó", "Tubará", "Palmar de Varela", "Ponedera", "Polonuevo",
    "Campo de la Cruz", "Repelón", "Luruaco", "Santa Lucía", "Manatí",
    "Candelaria", "Suan", "Santo Tomás",
  ],
  "Bogotá D.C.": ["Bogotá"],
  "Bolívar": [
    "Cartagena", "Magangué", "Mompox", "El Carmen de Bolívar", "Arjona",
    "Turbaco", "María la Baja", "San Juan Nepomuceno", "Zambrano", "Córdoba",
    "San Jacinto", "Ovejas", "Sincelejo", "Corozal", "San Onofre", "Tolú",
    "Calamar", "El Guamo", "Barranco de Loba", "San Martín de Loba",
    "Río Viejo", "Regidor", "Hatillo de Loba", "Pinillos", "Tiquisio",
    "San Pablo", "Cantagallo", "Morales", "Simití", "Santa Rosa del Sur",
    "Achí", "Montecristo", "Altos del Rosario", "Arenal", "Cicuco",
    "Clemencia", "Mahates", "Margarita", "Norosí", "San Estanislao",
    "San Fernando", "Santa Catalina", "Santa Rosa de Lima", "Soplaviento",
    "Talaigua Nuevo", "Villanueva", "Mahates",
  ],
  "Boyacá": [
    "Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Villa de Leyva",
    "Puerto Boyacá", "Garagoa", "Moniquirá", "Soatá", "Ráquira",
    "Guateque", "Aquitania", "Tenza", "Miraflores", "El Cocuy", "Güicán",
    "Berbeo", "Santa Sofía", "Muzo", "San Pablo de Borbur", "Otanche",
    "Cubará", "Saravena", "Paz de Río", "Belén", "Boavita", "Covarachía",
    "El Espino", "Guacamayas", "La Uvita", "San Mateo", "Capitanejo",
    "Betéitiva", "Cerinza", "Corrales", "Floresta", "Busbanzá", "Tutazá",
    "Toca", "Boyacá", "Ciénega", "Nuevo Colón", "Ramiriquí", "Rondón",
    "Tibaná", "Jenesano", "Úmbita", "Ventaquemada", "Tinjacá", "Saboyá",
    "Buenavista", "Coper", "Maripí", "Pauna", "Pesca", "Zetaquira",
    "Togüí", "Chitaraque", "Santana", "Santa Bárbara", "Sativanorte",
    "Sativasur", "Socha", "Susacón", "Tasco", "Chita", "Mongua",
    "Gámeza", "Labranzagrande", "Pisba", "Socotá",
  ],
  "Caldas": [
    "Manizales", "La Dorada", "Riosucio", "Chinchiná", "Villamaría",
    "Salamina", "Aguadas", "Anserma", "Manzanares", "Pácora",
    "Supía", "La Merced", "Neira", "Victoria", "Palestina",
    "Aranzazu", "Filadelfia", "La Victoria", "Marulanda", "Pensilvania",
    "Samaná", "Marquetalia", "Viterbo", "Belalcázar", "San José",
  ],
  "Caquetá": [
    "Florencia", "San Vicente del Caguán", "El Doncello", "El Paujil",
    "Cartagena del Chairá", "Puerto Rico", "Belén de los Andaquíes",
    "Albania", "Milán", "Solano", "Valparaíso", "La Montañita",
    "Curillo", "Morelia", "Solita",
  ],
  "Casanare": [
    "Yopal", "Villanueva", "Aguazul", "Tauramena", "Paz de Ariporo",
    "Trinidad", "Monterrey", "Maní", "Orocué", "Pore", "Nunchía",
    "Hato Corozal", "Recetor", "Sabanalarga", "San Luis de Palenque",
    "La Salina", "Sácama", "Támara", "Chameza",
  ],
  "Cauca": [
    "Popayán", "Santander de Quilichao", "Patía", "Puerto Tejada",
    "Piendamó", "Timbío", "Silvia", "Toribío", "Guapi",
    "López de Micay", "Timbiquí", "Rosas", "La Sierra", "Mercaderes",
    "Balboa", "El Bordo", "Bolívar", "Cajibío", "Caldono",
    "El Tambo", "Florencia", "Inzá", "Jambaló", "La Vega",
    "Miranda", "Morales", "Padilla", "Páez", "Planadas",
    "Puracé", "Rosas", "San Sebastián", "Santa Rosa",
    "Sotará", "Suárez", "Villa Rica",
  ],
  "Cesar": [
    "Valledupar", "Aguachica", "Bosconia", "La Paz", "Codazzi",
    "Curumaní", "Chimichagua", "El Paso", "Gamarra", "Chiriguaná",
    "La Jagua de Ibirico", "Pailitas", "Pueblo Bello", "Becerril",
    "Astrea", "Manaure", "Tamalameque", "El Copey", "La Gloria",
    "Pelaya", "Río de Oro", "San Alberto", "San Diego", "San Martín",
    "González", "San Ángel",
  ],
  "Chocó": [
    "Quibdó", "Istmina", "Riosucio", "Tadó", "Bagadó", "Condoto",
    "Lloró", "Bahía Solano", "Acandí", "Juradó", "El Cantón del San Pablo",
    "Sipí", "San José del Palmar", "Unión Panamericana", "Nóvita",
    "Cértegui", "Medio San Juan", "Atrato", "Bagadó", "Bojayá",
    "Carmen del Darién", "Litoral del San Juan", "Medio Atrato",
    "Medio Baudó", "Nuquí", "Río Iro", "Río Quito", "El Carmen de Atrato",
    "San Pedro de Urabá", "Under Atrato",
  ],
  "Córdoba": [
    "Montería", "Cereté", "Lorica", "Sahagún", "Planeta Rica",
    "Montelíbano", "Puerto Libertador", "Tierralta", "Valencia",
    "San Pelayo", "Ciénaga de Oro", "San Carlos", "Chinú", "Ayapel",
    "Buenavista", "La Apartada", "Purísima", "San Andrés de Sotavento",
    "Tuchín", "Canalete", "Los Córdobas", "Moñitos", "San Bernardo del Viento",
    "San Antonio de Palmito", "Cotorra", "Chima", "Momil", "Pueblo Nuevo",
    "San José de Uré",
  ],
  "Cundinamarca": [
    "Soacha", "Fusagasugá", "Facatativá", "Zipaquirá", "Chía", "Mosquera",
    "Madrid", "Cajicá", "Tocancipá", "Funza", "Ubaté", "Girardot",
    "Guaduas", "La Mesa", "Sibaté", "Cota", "Tenjo", "Sopó", "Tabio",
    "Subachoque", "Bojacá", "El Rosal", "Nemocón", "Villapinzón",
    "Chocontá", "Sesquilé", "Guasca", "La Calera", "Gachancipá",
    "Anapoima", "Apulo", "Arbeláez", "Beltrán", "Bituima",
    "Caparrapí", "Chaguaní", "Chipaque", "El Colegio", "El Peñón",
    "Fómeque", "Fosca", "Gachalá", "Gachetá", "Granada",
    "Guataquí", "Guayabal de Síquima", "Gutiérrez", "Junín",
    "La Palma", "La Peña", "Lenguazaque", "Macheta", "Manta",
    "Medina", "Nilo", "Nocaima", "Pandi", "Paratebueno",
    "Pasca", "Puerto Salgar", "Pulí", "Quebradanegra", "Quipile",
    "San Bernardo", "San Cayetano", "San Francisco", "San Juan de Rioseco",
    "Sasaima", "Silvania", "Simijaca", "Supatá", "Susa",
    "Sutatausa", "Tausa", "Tena", "Tibacuy", "Tibirita",
    "Tocaima", "Topaipí", "Útica", "Venecia", "Vergara",
    "Vianí", "Villagómez", "Villeta", "Viotá", "Yacopí",
    "Zipacón",
  ],
  "Guainía": [
    "Inírida", "Barranco Minas", "Mapiripana", "San Felipe",
    "Puerto Colombia", "La Guadalupe", "Cacahual", "Pana Pana", "Morichal",
  ],
  "Guaviare": [
    "San José del Guaviare", "El Retorno", "Calamar", "Miraflores",
  ],
  "Huila": [
    "Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre",
    "Rivera", "Palermo", "Colombia", "Hobo", "Guadalupe",
    "San Agustín", "Isnos", "Timaná", "Acevedo", "Suaza",
    "Tarqui", "Gigante", "Algeciras", "Tesalia", "El Agrado",
    "La Argentina", "Nátaga", "Saladoblanco", "Santa María",
    "Teruel", "Yaguará", "Aipe", "Tello", "Baraya", "Villavieja",
    "Oporapa", "Paicol", "Palermo",
  ],
  "La Guajira": [
    "Riohacha", "Maicao", "Uribia", "Manaure", "Fonseca",
    "San Juan del Cesar", "Albania", "Dibulla", "Barrancas",
    "Distracción", "El Molino", "Hatonuevo", "La Jagua del Pilar",
    "Urumita", "Villanueva",
  ],
  "Magdalena": [
    "Santa Marta", "Ciénaga", "Fundación", "El Banco", "Pivijay",
    "Aracataca", "Plato", "Zona Bananera", "El Retén",
    "Santa Bárbara de Pinto", "Salamina", "Concordia", "Chivolo",
    "Algarrobo", "Nueva Granada", "Tenerife", "Guamal",
    "Pijiño del Carmen", "San Zenón", "Zapayán", "Remolino",
    "Sitionuevo", "Cerro de San Antonio", "Pedraza", "San Sebastián",
    "Chibolo", "El Piñón", "Puebloviejo", "Sabanas de San Ángel",
    "Sitio Nuevo",
  ],
  "Meta": [
    "Villavicencio", "Acacías", "Restrepo", "Granada", "Guamal",
    "La Macarena", "Lejanías", "Mapiripán", "Mesetas",
    "Puerto Concordia", "Puerto Gaitán", "Puerto Lleras", "Puerto López",
    "Puerto Rico", "San Carlos de Guaroa", "San Juan de Arama",
    "San Martín", "Vistahermosa", "Barranca de Upía", "Cubarral",
    "El Dorado", "Fuente de Oro", "El Calvario", "El Castillo",
    "Castilla la Nueva", "San Juanito", "Uribe",
  ],
  "Nariño": [
    "Pasto", "Tumaco", "Ipiales", "Túquerres", "La Unión",
    "Samaniego", "El Charco", "Olaya Herrera", "Barbacoas", "Cumbal",
    "Ricaurte", "Chachagüí", "Guachucal", "La Florida", "Leiva",
    "Linares", "Los Andes de Cocha", "Magüí Payán", "Mallama",
    "Mosquera", "Roberto Payán", "Rosario", "Santacruz", "Sapuyes",
    "Santa Bárbara", "Tablón de Gómez", "Taminango", "Tangua",
    "La Cruz", "Colón", "Albán", "Aldana", "Ancuyá", "Arboleda",
    "Belén", "Buesaco", "El Tambo", "Funes", "Gualmatán",
    "Iles", "Imués", "Nariño", "Ospina", "Policarpa",
    "Potosí", "Providencia", "Puerres", "Pupiales", "San Bernardo",
    "San Lorenzo", "San Pablo", "San Pedro de Cartago", "Sandoná",
    "Sotomayor", "Talaigua", "Yacuanquer",
  ],
  "Norte de Santander": [
    "Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios",
    "El Zulia", "Tibú", "Sardinata", "Convención", "Hacarí",
    "La Playa", "El Carmen", "Ábrego", "Teorama", "El Tarra",
    "Salazar", "Chinácota", "Herrán", "Labateca", "Mutiscua",
    "Pamplonita", "Puerto Santander", "Ragonvalia", "Silos", "Toledo",
    "Bucarasica", "Cachirá", "Cáchira", "Cúcuta", "Durania",
    "El Castillo", "Gramalote", "La Esperanza", "Lourdes",
    "San Calixto", "San Cayetano", "Santiago", "Villa Caro",
  ],
  "Putumayo": [
    "Mocoa", "Puerto Asís", "Orito", "La Hormiga", "Puerto Leguizamo",
    "Sibundoy", "Colón", "San Francisco", "Santiago", "Valle del Guamuez",
    "Villagarzón", "Puerto Caicedo", "Puerto Guzmán",
  ],
  "Quindío": [
    "Armenia", "Calarcá", "Montenegro", "Quimbaya", "La Tebaida",
    "Filandia", "Salento", "Buenavista", "Circasia", "Córdoba",
    "Génova", "Pijao",
  ],
  "Risaralda": [
    "Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia",
    "Belén de Umbría", "Apía", "Guática", "Marsella", "Mistrató",
    "Pueblo Rico", "Quinchía", "Santuario", "Balboa",
  ],
  "San Andrés y Providencia": [
    "San Andrés", "Providencia",
  ],
  "Santander": [
    "Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja",
    "San Gil", "Socorro", "Barbosa", "Lebrija", "Málaga",
    "Rionegro", "Zapatoca", "Sabana de Torres", "Puerto Wilches",
    "Capitanejo", "Cimitarra", "Concepción", "Contratación",
    "Coromoro", "El Playón", "Galán", "Guaca", "Guavatá",
    "Guepsa", "Vélez", "Bolívar", "Mogotes", "San Joaquín",
    "San José de Miranda", "Santa Helena del Opón", "Suratá", "Tona",
    "Vetas", "Villanueva", "Betulia", "El Carmen de Chucurí",
    "El Peñón", "Encino", "Charalá", "Chipatá", "Curití",
    "El Guacamayo", "Encino", "Gámbita", "Hato", "Jesús María",
    "La Belleza", "La Paz", "Landázuri", "Macaravita", "Matanza",
    "Ocamonte", "Oiba", "Onzaga", "Palmar", "Palmas del Socorro",
    "Páramo", "Pinchote", "Puente Nacional", "Puerto Parra",
    "San Andrés", "San Benito", "San Vicente de Chucurí",
    "Santa Bárbara", "Simacota", "Sucre", "Valle de San José",
    "Vélez", "Aguada", "Albania", "Aratoca",
  ],
  "Sucre": [
    "Sincelejo", "Corozal", "Sampués", "Tolú", "Morroa",
    "San Marcos", "San Onofre", "Ovejas", "Caimito", "Coloso",
    "Chalán", "El Roble", "Galeras", "Guaranda", "La Unión",
    "Los Palmitos", "Majagual", "Palmito", "Sincé", "Sucre",
    "Tolú Viejo", "San Benito Abad", "San Luis de Sincé",
    "San Pedro", "Santiago de Tolú",
  ],
  "Tolima": [
    "Ibagué", "Espinal", "Melgar", "Líbano", "Purificación",
    "Chaparral", "Honda", "Flandes", "Mariquita", "Armero-Guayabal",
    "Ataco", "Coyaima", "Cunday", "Dolores", "Fresno", "Guamo",
    "Herveo", "Icononzo", "Lérida", "Murillo", "Natagaima",
    "Ortega", "Palocabildo", "Piedras", "Planadas", "Prado",
    "Rioblanco", "Roncesvalles", "Rovira", "San Antonio", "San Luis",
    "Santa Isabel", "Saldaña", "Suárez", "Valle de San Juan",
    "Venadillo", "Villahermosa", "Villarrica", "Alvarado", "Ambalema",
    "Anzoátegui", "Cajamarca", "Carmen de Apicalá", "Casabianca",
    "Coello", "El Espinal",
  ],
  "Valle del Cauca": [
    "Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago",
    "Florida", "Sevilla", "Yumbo", "Candelaria", "El Cerrito",
    "Pradera", "Roldanillo", "Riofrío", "La Victoria", "Obando",
    "Alcalá", "Ansermanuevo", "Argelia", "Bolívar", "Bugalagrande",
    "Caicedonia", "Calima", "Dagua", "El Águila", "El Cairo",
    "El Dovio", "Ginebra", "Guacarí", "Jamundí", "La Cumbre",
    "La Unión", "Restrepo", "San Pedro", "Toro", "Trujillo",
    "Ulloa", "Versalles", "Vijes", "Yotoco", "Zarzal",
    "Andalucía", "Ansermanuevo", "Belalcázar", "La Victoria",
    "Montebello",
  ],
  "Vaupés": [
    "Mitú", "Carurú", "Taraira", "Yavaraté", "Pacoa",
  ],
  "Vichada": [
    "Puerto Carreño", "La Primavera", "Santa Rosalía", "Cumaribo",
  ],
};
